export const menu = [
  { name: "Home", path: "/" },
  {
    name: "Rice Purity Score Meaning",
    path: "/what-does-the-rice-purity-test-score-mean",
  },
  {
    name: "Rice Purity Results",
    path: "/rice-purity-results",
  },
  {
    name: "Blog",
    path: "/blog",
  },
  { name: "Privacy Policy", path: "/privacy-policy" },
  { name: "Contact us", path: "/contact" },
];

export const blogLinks = [
  { name: "Rice Purity Test Explained: How Does It Work and Why Do People Take It?", path: "/blog/rice-purity-test-explained-how-does-it-work-and-why-do-people-take-it" },
  { name: "The History and Evolution of the Rice Purity Test", path: "/blog/history-evolution-rice-purity-test" },
  { name: "", path: "/blog/rice-purity-test-questions-how-well-do-you-know-yourself" },
  { name: "Rice Purity Test Questions: How Well Do You Know Yourself?", path: "/blog/" },
  { name: "What Is the Rice Purity Test and Why Is It So Popular?", path: "/blog/rice-purity-test-popularity-college-high-school-students" },
  { name: "Ricepurity Score: Is It a Reflection of Your True Self?", path: "/blog/ricepurity-score-reflection-true-self" },
  { name: "Rice Purity Test Scoring: How Is Your Innocence Calculated", path: "/blog/rice-purity-test-scoring-how-is-your-innocence-calculated" },
  { name: "The Rice Purity Test: A Fun Way to Test Your Morals?", path: "/blog/the-rice-purity-test-a-fun-way-to-test-your-morals" },
  { name: "Ricepurity Test: How Accurate Is It and Why Do We Take It?", path: "/blog/ricepurity-test-accuracy-and-purpose" },
  { name: "The Rice Purity Test 2.0: What's New in the Latest Version?", path: "/blog/rice-purity-test-2-0-whats-new" },
  { name: "The Rice Purity Test: A Reflection of Society's Morals?", path: "/blog/rice-purity-test-society-morals" },
  { name: "Why Taking the Rice Purity Test Is More Than Just a Fun Quiz", path: "/blog/why-taking-the-rice-purity-test-is-more-than-just-a-fun-quiz" },
  { name: "How to Interpret Your Rice Purity Test Score: Understanding the Results", path: "/blog/how-to-interpret-your-rice-purity-test-score-understanding-the-results" },
  { name: "Rice Purity Test Scores: Are You Really as Innocent as You Think?", path: "/blog/rice-purity-test-scores-are-you-really-as-innocent-as-you-think" },
  { name: "Rice Purity Test: Can It Help You Improve Your Morals and Ethics?", path: "/blog/rice-purity-test-morals-ethics" },
  { name: "The Psychology Behind the Rice Purity Test: Why We Take It", path: "/blog/rice-purity-test-psychology-behind-why-we-take-it" },
  { name: "Rice Purity Test Meaning: Decoding the Message Behind Your Score", path: "/blog/rice-purity-test-meaning" },
  { name: "What Is the Rice Purity Test and Why Do Colleges Use It?", path: "/blog/rice-purity-test-colleges-why-used" },
  { name: "The Rice Purity Test: Does It Really Determine Your Character?", path: "/blog/rice-purity-test-does-it-really-determine-your-character" },
  { name: "Rice Purity Test Score Meaning: Understanding the Impact of Your Result", path: "/blog/rice-purity-test-score-meaning-understanding-the-impact-of-your-result" },
  { name: "The Rice Purity Test: Is It Harmless Fun or a Source of Stress?", path: "/blog/rice-purity-test-harmless-fun-or-source-of-stress" },
  { name: "Ricepuritytesting.com: The Ultimate Destination for Innocence Quizzes", path: "/blog/ricepuritytest-ultimate-destination-innocence-quizzes" },
  { name: "The Pros and Cons of Taking the Rice Purity Test", path: "/blog/the-pros-and-cons-of-taking-the-rice-purity-test" },
  { name: "Rice Purity Test Quiz: How Well Do You Know Your Morals?", path: "/blog/rice-purity-test-quiz-know-your-morals" },
  { name: "The Rice Purity Test: A Unique Way to Discover Your True Self", path: "/blog/rice-purity-test-discover-true-self" },
  { name: "The Rice Purity Test: Are You Really as Pure as You Claim to Be?", path: "/blog/the-rice-purity-test-are-you-really-as-pure-as-you-claim" },
  { name: "The Most Comprehensive Resource for Innocence Tests", path: "/blog/the-most-comprehensive-resource-for-innocence-tests" },
  { name: "Rice Purity Test Scoring System: How Is Your Innocence Judged?", path: "/blog/rice-purity-test-scoring-system-innocence-judged" },
  { name: "The Rice Purity Test: A Reflection of Society's Changing Morals?", path: "/blog/the-rice-purity-test-a-reflection-of-societys-changing-morals" },
  { name: "Rice Purity Test: What It Tells Us About Our Attitudes Towards Morality", path: "/blog/rice-purity-test-attitudes-morality" },
  { name: "The Truth Behind the Rice Purity Test: Everything You Need to Know", path: "/blog/the-truth-behind-the-rice-purity-test-everything-you-need-to-know" },
  { name: "Uncovering the Meaning of Your Rice Purity Score", path: "/blog/uncovering-meaning-rice-purity-score" },
  { name: "The Rice Purity Test: Can You Really Measure Someone's Innocence", path: "/blog/rice-purity-test-measure-innocence" },
  { name: "The Rice Purity Test and the Pressure to Fit In", path: "/blog/the-rice-purity-test-and-the-pressure-to-fit-in" },
];


export const footerMenu = [
  { name: "Rice Purity Test", path: "/" },
  {
    name: "Blog",
    path: "/blog",
  },
  { name: "Privacy Policy", path: "/privacy-policy" },
  { name: "Contact us", path: "/contact" },
];

export const testimonials = [
  `"I took the Rice Purity Test and was really surprised by how accurate it was. I learned a lot about myself and my values, and it was a great way to reflect on my journey so far." - Sarah B.`,
  `"I never knew how much I valued my purity until I took the Rice Purity Test. It was a great wake-up call and helped me set new goals for my future." - Mark D.`,
  `"I always thought I had a pretty good handle on my life and values, but the Rice Purity Test showed me areas where I could improve and grow. I'm grateful for the insights it provided." - Emily K.`,
  `"I was hesitant to take the Rice Purity Test at first, but I'm glad I did. It gave me a new perspective on my relationships and what's truly important to me." - Jake R.`,
  `"I was nervous about taking the Rice Purity Test, but it ended up being a very positive experience. I learned so much about myself and feel more confident in my decisions going forward." - Rachel M.`,
  `"I took the Rice Purity Test with a group of friends and it was a lot of fun. It was also a great way to start a meaningful conversation and reflect on our lives together." - John C.`,
  `"I took the Rice Purity Test as a way to challenge myself and see where I stood. I was proud of my results and felt a sense of accomplishment after completing it." - Lisa P.`,
  `"I never considered the idea of purity in my life until I took the Rice Purity Test. It was eye-opening and helped me understand my values and beliefs on a deeper level." - Tyler L.`,
  `"I took the Rice Purity Test to see how I compared to my friends and was pleasantly surprised by my results. It was a great way to gauge my personal growth and progress." - Emily T.`,
  `"I took the Rice Purity Test as a way to hold myself accountable and make sure I was staying true to my values. I was proud of my results and feel more confident in the person I am becoming." - Mark R.`,
];

export const db = [
  "Do you know what it feels like to hold hands in a romantic way?",
  "Have you ever been in a serious relationship?",
  "Have you ever danced with someone in a suggestive way?",
  "Did you ever kissed a non-family member?",
  "Did you Kiss a non-family member on the lips?",
  "French kissed someone?",
  "French kissed someone in public?",
  "Have you ever kissed your girl/boyfriend on the neck?",
  "Do you like giving or receiving hickeys love-bite?",
  "Have you ever kissed someone for a couple of hours (non-stop)?",
  "Did you engage in a naughty game where the punishment of losers was stripping?",
  "Have you ever touched yourself while someone else was in the room?",
  "Has someone ever caught you while touching yourself?",
  "Do you read adult magazines or watch adult movies?",
  "Do you like to give or receive a sensually rub?",
  "Had or been given ‘blue balls’ (a.k.a. edging)?",
  "Did you do naughty things on FaceTime?",
  "Cheated on your partner?",
  "Purchased contraceptives?",
  "Used a toy with a partner?",
  "Ingested alcohol in a non-religious context?",
  "Played a drinking game?",
  "Been drunk?",
  "Faked sobriety to parents or teachers?",
  "Have you ever slept in your boy/girlfriend’s house?",
  "Have you ever got ridden of your roommate so you can do something naughty?",
  "Do you drink beverages?",
  "Have you ever fooled others to believe you’re sober while you were not?",
  "Have you ever had a rea-deal hangover?",
  "Had severe memory loss due to alcohol (blackout)?",
  "Used tobacco?",
  "Do you smoke?",
  "been one heigh to another heigh?",
  "Been put on disciplinary probation or suspended?",
  "Have you ever been called to the principal’s office for misbehavior?",
  "Have you ever swam in a pool where everyone (including you) was clothless?",
  "Urinated in public?",
  "Did someone ever called the cops on you for whatsoever reason?",
  "Have you ever tried to run away from the police?",
  "Had the police question you?",
  "Had the police handcuff you?",
  "Been arrested?",
  "Have you ever in jailed?",
  "Been convicted of a crime?",
  "Been convicted of a felony?",
  "Did you damage public/private properties on purpose?",
  "69 ?",
  "Joined the mile high club?",
  "Did you ever try in four different styles/positions?",
  "Have you ever met and slept with someone on the same day?",
  "Have you ever done it in a vehicle?",
  "Have you ever experienced outdoor something naughty?",
  "Would you like to do naughty things in a swimming pool?",
  "Have you ever being naughty with your partner while you or your partner’s parents were in another room?",
  "Have you ever had serious naughty activities while someone else was watching?",
  "Have you ever done naughty things in an aircraft?!",
  "Have you ever invited someone over just to do naughty things with them?",
  "Have you ever slept with someone notably older than you?",
  "Had an STI test due to reasonable suspicion?",
  "Had an STI?",
  "Had a pregnancy scare?",
  "Impregnated someone or been impregnated?",
  "Committed an act of voyeurism?",
  "Committed an act of incest?",
  "Engaged in bestiality?",
  "You rarely feel insecure",
  "You usually prefer to get your revenge rather than forgive?",
  "Avoid arguing, even when I disagree.?",
  "Your emotions control you more than you control them.?",
  "I enjoy being there for people when they are feeling sad.?",
  "Have you ever slept with 2 different people on the very same day?",
  "Did you have more than 5 partners in your life for personal relation?",
  "Do you have naughty photos/videos of you?",
  "Have you ever received money for physical satisfaction? Did you pay for it?",
  "Have you ever peeked at others while they were doing something naughty in their private space?",
  "Have you ever included an animal in your physical satisfaction activities?",
  "Made out in public?",
  "Paid for a premium dating site?",
  "Have you pierced anything below your neck?",
  "Have you ever thrown eggs at a house or car?",
  "Have you ever traveled 100 or more miles for the primary purpose of your pleasure?",
  "Have you ever been photographed or filmed your personal things?",
  "Have you ever blocked more than 10 people on snapchat?",
  "Have you ever held a grudge against someone?",
  "Have you ever invited someone just for their looks?",
  "Denied having had some physical relations with somebody, when you actually had?",
  "Have you ever shoplifted?",
  "Have you ever bought or sold anything on a black market? (fake products)",
  "Have read someone else's diary, text message, or snapchat without their knowledge and/or consent?",
  "Have you ever sung racist songs or said racist remarks?",
  "Have you ever lied about being in a band or a talent of yours to impress someone?",
  "Have you ever sent or received an anonymous obscene phone call?",
  "Have you ever gone out in public without clothes?",
  "Downloaded a virus on someone’s computer or broken someone’s phone?",
  "Spread a fake rumor about someone on purpose?",
  "Lied about being drunk or high to a family member or adult?",
  "Been put on probation or suspended from school?",
  "sent nudes?",
  "paid for a premium version of a dating app ?",
  "texted while driving?",
];
